Repository ManifoldScholar/manifold, pull requests merged in 2018-12, with the labels that each got.

#1700 [B] Return nil when style value is empty
  api/app/models/concerns/attachments.rb
  api/spec/models/concerns/attachment_spec.rb
  client/static/images/attachment_placeholders/large_landscape.png
  client/static/images/attachment_placeholders/medium.png
  client/static/images/attachment_placeholders/medium_landscape.png
  client/static/images/attachment_placeholders/medium_portrait.png
  client/static/images/attachment_placeholders/medium_square.png
  client/static/images/attachment_placeholders/small.png
  client/static/images/attachment_placeholders/small_landscape.png
  client/static/images/attachment_placeholders/small_portrait.png
  client/static/images/attachment_placeholders/small_square.png
Labels: needs review

#1703 [B] Sort users by name in permissions form
  client/src/backend/containers/permission/Form.js
Labels: needs review

#1702 [B] Fix Project#resource_tags returning relationship
  api/app/models/project.rb
Labels: needs review

#1701 [B] Fix audio resource mime type validations
  api/config/manifold.yml
Labels: needs review

#1706 [B] Fix error boundary lifecycle usages
  client/src/global/components/FatalError/Boundary.js
  client/src/global/components/FatalError/ClientTrace.js
  client/src/global/components/FatalError/index.js
Labels: needs review

#1711 [B] Fix FF dropdown option styles
  client/src/theme/Components/global/forms/_form-inputs-primary.scss
  client/src/theme/Components/global/forms/_list-filter.scss
Labels: needs review

#1730 [B] Fix frontend header menu positions
  client/src/theme/Components/global/_header-app.scss
Labels: needs review

#1678 [B] Display base model errors in FormContainer
  client/src/backend/containers/form/Form.js
  client/src/backend/containers/makers/Form.js
  client/src/backend/containers/stylesheet/__tests__/__snapshots__/Edit-test.js.snap
  client/src/backend/containers/text/__tests__/__snapshots__/Metadata-test.js.snap
Labels: needs review

#1739 [B] Hide tweet fetching if not configured
  api/app/services/tweet/fetcher.rb
  client/src/backend/containers/twitter-query/Edit.js
  client/src/backend/containers/twitter-query/__tests__/__snapshots__/Edit-test.js.snap
Labels: ready to accept

#1742 [B] Address OAuth regression
  api/app/controllers/oauth_controller.rb
  api/app/views/oauth/authorize.html.erb
  api/spec/requests/oauth_spec.rb
Labels: ready to accept

#1748 [WIP] Implement backend project layout interface
  client/src/backend/components/list/Orderable.js
  client/src/backend/components/project/Content/Block/helpers/resolver.js
  client/src/backend/components/project/Content/Block/in-list/Available.js
  client/src/backend/components/project/Content/Block/in-list/AvailablePlaceholder.js
  client/src/backend/components/project/Content/Block/in-list/Current.js
  client/src/backend/components/project/Content/Block/index.js
  client/src/backend/components/project/Content/Block/parts/Identity.js
  client/src/backend/components/project/Content/Block/types/Markdown.js
  client/src/backend/components/project/Content/Block/types/Resources.js
  client/src/backend/components/project/Content/Block/types/TOC.js
  client/src/backend/components/project/Content/Block/types/index.js
  client/src/backend/components/project/Content/index.js
  client/src/backend/components/project/Content/sections/Available.js
  client/src/backend/components/project/Content/sections/Current.js
  client/src/backend/components/project/Content/sections/parts/Header.js
  client/src/backend/components/project/Content/temporary/fake-project.js
  client/src/backend/components/project/index.js
  client/src/backend/containers/project/Content.js
  client/src/backend/containers/project/index.js
  client/src/backend/containers/route-containers.js
  client/src/backend/routes.js
  client/src/theme/Components/backend/project/_content_blocks.scss
  client/src/theme/Components/backend/project/_index.scss
  client/src/theme/theme.scss
Labels: in progress
