Repository ManifoldScholar/manifold, pull requests merged in 2018-11, with the labels that each got.

#1580 [B] Reload text before passing to PostProcessor
  api/app/services/ingestions/compiler.rb
Labels: needs review

#1579 [B] Fix duplicate request on projects search
  client/src/containers/frontend/Projects.js
Labels: needs review

#1552 [B] Improve open graph meta tags
  api/app/controllers/concerns/validation.rb
  api/app/models/settings.rb
  client/src/components/frontend/Project/__tests__/Events-test.js
  client/src/components/global/HeadContent.js
  client/src/components/global/SignInUp/Create.js
  client/src/config.js
  client/src/containers/Manifold.js
  client/src/containers/backend/Settings/General.js
  client/src/containers/backend/Settings/__tests__/__snapshots__/General-test.js.snap
  client/src/containers/frontend/Page.js
Labels: needs review

#1582 [B] Allow project titles to be formatted
  api/app/models/project.rb
  api/app/serializers/project_serializer.rb
  client/src/components/backend/List/__tests__/__snapshots__/Orderable-test.js.snap
  client/src/components/backend/List/__tests__/__snapshots__/SimpleList-test.js.snap
  client/src/components/backend/Project/ListItem.js
  client/src/components/backend/Project/__tests__/__snapshots__/ListItem-test.js.snap
  client/src/components/backend/ProjectCollection/ProjectCover.js
  client/src/components/backend/ProjectCollection/__tests__/__snapshots__/ProjectCover-test.js.snap
  client/src/components/frontend/Project/Cover.js
  client/src/components/frontend/Project/Events.js
  client/src/components/frontend/Project/Hero.js
  client/src/components/frontend/Project/Thumbnail.js
  client/src/components/frontend/Project/__tests__/__snapshots__/Detail-test.js.snap
  client/src/components/frontend/Project/__tests__/__snapshots__/Hero-test.js.snap
  client/src/components/frontend/Project/__tests__/__snapshots__/Thumbnail-test.js.snap
  client/src/components/frontend/ProjectCollection/__tests__/__snapshots__/Detail-test.js.snap
  client/src/components/frontend/ProjectCollection/__tests__/__snapshots__/Summary-test.js.snap
  client/src/components/frontend/ProjectList/__tests__/__snapshots__/Following-test.js.snap
  client/src/components/frontend/ProjectList/__tests__/__snapshots__/Grid-test.js.snap
  client/src/components/global/Developer/__tests__/__snapshots__/Debugger-test.js.snap
  client/src/components/global/Project/CoverButton.js
  client/src/components/reader/Header.js
  client/src/containers/backend/Collection/New.js
  client/src/containers/backend/Collection/Wrapper.js
  client/src/containers/backend/Dashboards/__tests__/__snapshots__/Admin-test.js.snap
  client/src/containers/backend/Dashboards/__tests__/__snapshots__/Author-test.js.snap
  client/src/containers/backend/Project/Wrapper.js
  client/src/containers/backend/Project/__tests__/__snapshots__/Permissions-test.js.snap
  client/src/containers/backend/ProjectCollection/Detail/__tests__/__snapshots__/Manual-test.js.snap
  client/src/containers/backend/ProjectCollection/Detail/__tests__/__snapshots__/Smart-test.js.snap
  client/src/containers/backend/ProjectCollection/__tests__/__snapshots__/ManageProjects-test.js.snap
  client/src/containers/backend/Resource/New.js
  client/src/containers/backend/Resource/Wrapper.js
  client/src/containers/backend/ResourceImport/Wrapper.js
  client/src/containers/backend/Text/Wrapper.js
  client/src/containers/frontend/CollectionDetail.js
  client/src/containers/frontend/ProjectDetail.js
  client/src/containers/frontend/ProjectResources.js
  client/src/containers/frontend/ResourceDetail.js
  client/src/containers/frontend/__tests__/__snapshots__/Featured-test.js.snap
  client/src/containers/frontend/__tests__/__snapshots__/Following-test.js.snap
  client/src/containers/frontend/__tests__/__snapshots__/Home-test.js.snap
  client/src/containers/frontend/__tests__/__snapshots__/ProjectCollectionDetail-test.js.snap
  client/src/containers/frontend/__tests__/__snapshots__/ProjectDetail-test.js.snap
  client/src/containers/reader/Section.js
  client/src/test/fixtures/entity.js
Labels: needs review

#1583 [C] Always use HTML in DetailHeader title
  client/src/components/backend/Navigation/DetailHeader.js
  client/src/components/backend/Navigation/__tests__/__snapshots__/DetailHeader-test.js.snap
  client/src/components/backend/ProjectCollection/__tests__/__snapshots__/Header-test.js.snap
  client/src/containers/backend/Collection/Wrapper.js
  client/src/containers/backend/Collection/__tests__/__snapshots__/New-test.js.snap
  client/src/containers/backend/Project/__tests__/__snapshots__/New-test.js.snap
  client/src/containers/backend/Project/__tests__/__snapshots__/Wrapper-test.js.snap
  client/src/containers/backend/ProjectCollection/__tests__/__snapshots__/Wrapper-test.js.snap
  client/src/containers/backend/Resource/Wrapper.js
  client/src/containers/backend/Resource/__tests__/__snapshots__/New-test.js.snap
  client/src/containers/backend/Text/__tests__/__snapshots__/Wrapper-test.js.snap
Labels: needs review

#1585 [B] Reload text before passing to PostProcessor
  api/app/services/ingestions/compiler.rb
Labels: needs review

#1574 [B] Allow text titles to be formatted
  api/app/models/text.rb
  api/app/models/text_title.rb
  api/app/serializers/text_serializer.rb
  api/spec/models/text_spec.rb
  client/src/components/frontend/Text/Cover.js
  client/src/components/frontend/Text/Thumbnail.js
  client/src/components/frontend/Text/__tests__/__snapshots__/Thumbnail-test.js.snap
  client/src/components/frontend/TextList/__tests__/__snapshots__/Grouped-test.js.snap
  client/src/components/frontend/TextList/__tests__/__snapshots__/Published-test.js.snap
  client/src/components/reader/Annotation/Popup/Secondary/Share.js
  client/src/components/reader/Header.js
  client/src/components/reader/TextTitles.js
  client/src/components/reader/__tests__/__snapshots__/TextTitles-test.js.snap
  client/src/containers/backend/Project/Texts.js
  client/src/containers/backend/Project/__tests__/__snapshots__/Texts-test.js.snap
  client/src/containers/backend/Text/Wrapper.js
  client/src/containers/reader/Reader.js
  client/src/containers/reader/Section.js
  client/src/containers/reader/__tests__/__snapshots__/Reader-test.js.snap
  client/src/test/fixtures/entity.js
Labels: needs review

#1587 [B] Allow marketeer CRUD abilities on ProjectCollection
  api/app/authorizers/application_authorizer.rb
  api/app/authorizers/project_collection_authorizer.rb
  api/spec/authorizers/project_collection_authorizer_spec.rb
Labels: needs review

#1590 [B] Update rails-html-sanitizer dependencies
  api/Gemfile.lock
Labels: needs review

#1592 [B] Allow project collection slugs to be edited
  api/app/controllers/concerns/validation.rb
  client/src/containers/backend/ProjectCollection/Settings.js
  client/src/containers/backend/ProjectCollection/__tests__/__snapshots__/Settings-test.js.snap
Labels: needs review

#1595 [B] Focus on input in project collection drawer
  client/src/containers/backend/ProjectCollection/New.js
  client/src/containers/backend/ProjectCollection/Settings.js
Labels: needs review

#1594 [B] Use formatted project collection descriptions
  api/app/serializers/project_collection_serializer.rb
  client/src/components/frontend/ProjectCollection/Detail.js
  client/src/components/frontend/ProjectCollection/Summary.js
  client/src/containers/frontend/ProjectCollectionDetail.js
Labels: needs review

#1597 [C] Merge branch 'v2.0.x' into master
  api/Gemfile.lock
  api/app/controllers/concerns/api/v1/resourceful.rb
  api/app/controllers/concerns/validation.rb
  api/app/models/settings.rb
  client/src/components/frontend/Project/__tests__/Events-test.js
  client/src/components/global/HeadContent.js
  client/src/components/global/SignInUp/Create.js
  client/src/config.js
  client/src/containers/Manifold.js
  client/src/containers/backend/Settings/General.js
  client/src/containers/backend/Settings/__tests__/__snapshots__/General-test.js.snap
  client/src/containers/frontend/Page.js
  client/yarn.lock
Labels: needs review

#1599 [C] Lint app
  api/app/models/collection_project.rb
  client/src/components/backend/Layout/BackendPanel.js
  client/src/components/backend/Page/ListItem.js
  client/src/components/frontend/ProjectCollection/Summary.js
  client/src/containers/backend/ProjectCollection/Wrapper.js
  client/src/containers/frontend/Home.js
  client/src/containers/global/HigherOrder/__mocks__/withFormContext.js
  client/src/containers/global/NotFound.js
  client/src/helpers/labelId.js
Labels: needs review

#1606 [B] Add charset to head meta content
  client/src/components/global/HeadContent.js
Labels: needs review

#1609 [B] Fix migations using attachment columns
  api/db/migrate/20160511233642_add_attachment_avatar_to_users.rb
  api/db/migrate/20161018201521_add_fields_to_projects.rb
  api/db/migrate/20161020182356_add_fields_to_maker.rb
  api/db/migrate/20161024193939_add_attachment_to_ingestion_source.rb
  api/db/migrate/20161104222831_add_fields_to_resources.rb
  api/db/migrate/20161105231153_create_collections.rb
  api/db/migrate/20170126191544_add_attachment_press_logo_to_settings.rb
  api/db/migrate/20170320182809_add_attachment_types_to_resources.rb
  api/db/migrate/20170330185847_create_ingestions.rb
  api/db/migrate/20170912223135_create_features.rb
  api/db/migrate/20180219200744_create_resource_import_and_resource_import_rows.rb
  api/db/migrate/20180821160457_add_attachment_published_text_to_projects.rb
  api/db/migrate/20180921160539_add_press_logo_footer_to_settings.rb
  api/db/schema.rb
  api/lib/paperclip_migrator.rb
Labels: needs review

#1610 [B] Validate slug uniqueness
  api/app/models/concerns/validates_slug_presence.rb
  api/config/initializers/30_monkeypatches.rb
  api/lib/patches/friendly_id_uniqueness.rb
Labels: needs review

#1608 [C] Refactor app header to better handle logos
  client/src/components/backend/Layout/Header.js
  client/src/components/backend/Layout/__tests__/__snapshots__/Header-test.js.snap
  client/src/components/frontend/Layout/Header.js
  client/src/components/frontend/Layout/__tests__/__snapshots__/Header-test.js.snap
  client/src/components/global/Navigation/Primary.js
  client/src/components/global/Navigation/Static.js
  client/src/components/global/PressLogo.js
  client/src/components/global/SVG/Icon/ManifoldLogo.js
  client/src/components/global/SVG/Icon/index.js
  client/src/components/global/SignInUp/Overlay.js
  client/src/components/global/SignInUp/__tests__/__snapshots__/Overlay-test.js.snap
  client/src/components/global/__tests__/__snapshots__/PressLogo-test.js.snap
  client/src/containers/backend/__tests__/__snapshots__/Backend-test.js.snap
  client/src/containers/frontend/__tests__/__snapshots__/Frontend-test.js.snap
  client/src/theme/Components/global/_header-app.scss
  client/src/theme/Components/global/_header-logo.scss
  client/src/theme/Components/global/_index.scss
  client/src/theme/Components/global/_notification.scss
  client/src/theme/Components/global/_overlay-full-primary.scss
  client/src/theme/STACSS/_structure.scss
  client/yarn.lock
Labels: needs revision

#1620 [B] Improve ingestion source path handling
  api/app/services/ingestions/concerns/file_operations.rb
  api/app/services/ingestions/converters/ms_word.rb
  api/spec/data/ingestion/manifest/badly_named_sources.zip
  api/spec/services/ingestions/concerns/file_operations_spec.rb
  api/spec/services/ingestions/ingestor_spec.rb
Labels: needs review

#1624 [B] Improve ingestion error reporting
  api/app/models/ingestion.rb
Labels: needs review

#1628 [C] Report file conversion during ingestion
  api/app/services/ingestions/converters/abstract_converter.rb
  api/config/locales/services/ingestions/en.yml
Labels: needs review

#1639 [C] Add ingestion spec fixture with symbols in name
  api/spec/data/ingestion/manifest/badly_named_sources.zip
  api/spec/services/ingestions/concerns/file_operations_spec.rb
Labels: needs review

#1645 [B] Text sections without names are valid
  api/app/services/ingestions/compilers/text_section.rb
Labels: needs review

#1625 [F] Allow favicon to be set per installation
  api/app/controllers/concerns/validation.rb
  api/app/lib/updaters/settings.rb
  api/app/models/concerns/attachments.rb
  api/app/models/settings.rb
  api/app/serializers/settings_serializer.rb
  api/app/services/attachments/style_configurer.rb
  api/config/manifold.yml
  api/db/migrate/20181109165055_add_favicon_to_settings.rb
  api/db/schema.rb
  client/src/containers/backend/Settings/Theme.js
  client/src/containers/backend/Settings/__tests__/__snapshots__/Theme-test.js.snap
  client/src/helpers/Html.js
Labels: ready to accept

#1650 [B] PaperclipMigrator supports versionless uploaders
  api/lib/paperclip_migrator.rb
Labels: needs review

#1653 [B] Allow markdown in footer copyright text
  api/app/models/settings.rb
  api/app/serializers/settings_serializer.rb
  client/src/components/frontend/Layout/Footer.js
  client/src/components/frontend/Layout/__tests__/__snapshots__/Footer-tests.js.snap
  client/src/containers/backend/__tests__/__snapshots__/Backend-test.js.snap
  client/src/containers/frontend/__tests__/__snapshots__/Frontend-test.js.snap
  client/src/test/fixtures/entity.js
Labels: needs review

#1654 [F] Allow sign up link to be disabled per feature
  api/app/controllers/concerns/validation.rb
  api/app/serializers/feature_serializer.rb
  api/db/migrate/20181114185600_add_include_sign_up_to_features.rb
  api/db/schema.rb
  client/src/components/frontend/Layout/Splash.js
  client/src/containers/backend/Features/General.js
Labels: needs review

#1657 [B] Fix reingestion failing on cover source report
  api/app/services/ingestions/compilers/text.rb
  api/config/locales/services/ingestions/en.yml
Labels: needs review

#1665 [B] Fix project activity route nesting
  client/src/routes.js
Labels: needs review

#1672 [B] Fix model creation with associations
  api/spec/requests/project_collections_spec.rb
  client/src/containers/backend/Form/Form.js
Labels: needs review

#1676 [B] Fix regression in Permission creation
  client/src/containers/backend/Form/Form.js
  client/src/containers/backend/Permission/Form.js
Labels: needs review

#1681 [B] Fix duped media filenames in manifest doc ingestions
  api/app/services/ingestions/converters/ms_word.rb
  api/spec/data/ingestion/ms_word/docs_with_media.zip
  api/spec/services/ingestions/converters/ms_word_spec.rb
Labels: needs review

#1685 [B] Improve ingestion file rejection criteria
  api/app/services/ingestions/concerns/file_operations.rb
Labels: needs review
