Repository ManifoldScholar/manifold, pull requests merged in 2018-07, with the labels that each got.

#1138 [B] Fix layout issues at reader table breakpoints
  client/src/theme/Components/reader/_header-reader.scss
  client/src/theme/Components/reader/notation/_notation-viewer.scss
  client/src/theme/Components/reader/notation/_viewer.scss
Labels: needs review

#1154 [B] Fix .flv files not being selectable in upload
  client/src/components/backend/Form/Upload.js
  client/src/components/backend/Resource/Form/Kind/__tests__/__snapshots__/Video-test.js.snap
Labels: needs review

#1153 [B] Improve ogg file acceptance
  api/config/manifold.yml
  client/src/components/backend/Form/Upload.js
  client/src/components/backend/Resource/Form/Kind/__tests__/__snapshots__/Audio-test.js.snap
Labels: needs review

#1157 [B] Add default paragraph margins in reader
  client/src/theme/Components/reader/_text-section.scss
Labels: needs review

#1149 [B] Fix resource cards not using full space on project detail
  api/app/serializers/project_serializer.rb
  client/src/theme/Components/browse/project/_resource-thumbnail-list.scss
Labels: needs review

#1148 [C] Add .gitkeep to api/tmp/sockets
  api/tmp/sockets/.gitkeep
Labels: needs review

#1150 [B] Fix private annotations being wrongly visible
  api/app/models/annotation.rb
Labels: ready to accept

#1152 [B] Add error state to audio player
  client/src/components/frontend/Resource/Player/Audio.js
  client/src/theme/Components/browse/resource/_audio-player.scss
  client/src/theme/assets/svg/fonts/manicon/octagon-bang.svg
Labels: needs review

#1155 [B] Stop audio playback when reader overlay closes
  client/src/components/frontend/Resource/Player/Audio.js
Labels: needs review

#1156 [B] Remove duplicate social fields from project backend
  client/src/containers/backend/Project/ProjectPage.js
  client/src/containers/backend/Project/__tests__/__snapshots__/ProjectPage-test.js.snap
Labels: needs review

#1170 [B] Close comment editor after successful post
  client/src/containers/global/Comment/Editor.js
Labels: ready to accept

#1145 Update follow/unfollow project interaction accessibility
  client/src/components/frontend/Project/Follow.js
  client/src/components/frontend/Project/__tests__/__snapshots__/Following-test.js.snap
  client/src/components/frontend/Project/__tests__/__snapshots__/Thumbnail-test.js.snap
  client/src/components/frontend/ProjectList/__tests__/__snapshots__/CoversGrid-test.js.snap
  client/src/components/frontend/ProjectList/__tests__/__snapshots__/Grid-test.js.snap
  client/src/components/frontend/ProjectList/__tests__/__snapshots__/SummaryGrid-test.js.snap
  client/src/containers/frontend/__tests__/__snapshots__/Featured-test.js.snap
  client/src/containers/frontend/__tests__/__snapshots__/Following-test.js.snap
  client/src/containers/frontend/__tests__/__snapshots__/Home-test.js.snap
Labels: accessibility, ready to accept

#1173 [B] Fix incorrect entity count when 0 exist
  client/src/components/global/Utility/EntityCount.js
Labels: needs review

#1176 [B] Fix reader overlay close routes
  client/src/containers/reader/Notation/Collection/Detail.js
  client/src/containers/reader/Notation/Collection/__tests__/__snapshots__/Detail-test.js.snap
  client/src/containers/reader/Notation/Resource/Detail.js
  client/src/containers/reader/Notation/Resource/__tests__/__snapshots__/Detail-test.js.snap
Labels: needs review

#1182 [B] Implement default publisher/place behavior
  api/app/controllers/concerns/validation.rb
  api/app/models/project.rb
  api/db/migrate/20180710155830_rename_settings_default_place_of_publication.rb
  api/db/schema.rb
  api/spec/models/project_spec.rb
  client/src/containers/backend/Project/General.js
  client/src/containers/backend/Project/__tests__/__snapshots__/General-test.js.snap
  client/src/containers/backend/Settings/General.js
Labels: needs review

#1184 [F] Add variant download list to resource detail page
  api/app/models/concerns/resource_attribute_resets.rb
  api/app/serializers/resource_serializer.rb
  client/src/components/frontend/Resource/Detail.js
  client/src/components/frontend/Resource/Link.js
  client/src/components/frontend/Resource/VariantList.js
  client/src/components/frontend/Resource/__tests__/__snapshots__/Detail-test.js.snap
  client/src/components/frontend/Resource/index.js
  client/src/containers/frontend/__tests__/__snapshots__/ResourceDetail-test.js.snap
  client/src/theme/Components/browse/resource/_index.scss
  client/src/theme/Components/browse/resource/_variant-list.scss
Labels: needs review, under discussion

#1190 [B] Update audio player styles for ie11
  client/src/components/frontend/Resource/Player/Audio.js
  client/src/theme/Components/browse/resource/_audio-player.scss
Labels: needs revision

#1191 [B] Fix document ingestion text section/source identifiers
  api/app/services/ingestions/strategies/document.rb
  api/app/services/ingestions/strategy/document/ingestion_source.rb
  api/app/services/ingestions/strategy/document/inspector.rb
  api/spec/services/ingestions/compiler_spec.rb
  api/spec/services/ingestions/ingestor_spec.rb
  api/spec/services/ingestions/strategies/document_spec.rb
Labels: needs review

#1195 [B] Fix the positioning and styles for the left side notation thumbnails in the reader
  client/src/components/reader/Annotation/Popup/Wrapper.js
  client/src/components/reader/Notation/Viewer/Fader.js
  client/src/components/reader/Notation/Viewer/List.js
Labels: needs review

#1199 [B] Fix latex ingestions failing due to content type
  api/app/services/ingestions/converters/latex.rb
  api/app/services/ingestions/converters/ms_word.rb
  api/config/manifold.yml
  api/spec/services/ingestions/strategies/document_spec.rb
Labels: needs review

#1210 [B] Fix search menu slide off transition
  client/src/theme/Components/reader/_header-reader.scss
Labels: bug

#1197 [C] Replace velocity-react with react-collapse
  client/package.json
  client/src/components/frontend/ResourceCollection/__tests__/Detail-test.js
  client/src/components/frontend/ResourceList/Slide/Caption.js
  client/src/components/frontend/ResourceList/Slide/__tests__/Caption-test.js
  client/src/components/frontend/ResourceList/__tests__/Slideshow-test.js
  client/src/components/reader/Notation/Collection/__tests__/Detail-test.js
  client/src/components/reader/Notation/Collection/__tests__/__snapshots__/Detail-test.js.snap
  client/src/components/reader/Notes/Partial/Group.js
  client/src/components/reader/Notes/Partial/__tests__/__snapshots__/Group-test.js.snap
  client/src/components/reader/Notes/__tests__/__snapshots__/FilteredList-test.js.snap
  client/src/containers/frontend/__tests__/CollectionDetail-test.js
  client/src/containers/frontend/__tests__/__snapshots__/CollectionDetail-test.js.snap
  client/src/containers/reader/Notation/Collection/__tests__/Detail-test.js
  client/src/containers/reader/Notation/Collection/__tests__/__snapshots__/Detail-test.js.snap
  client/src/theme/Components/browse/collection/_resource-slideshow.scss
  client/src/theme/Components/reader/notation/_detail.scss
  client/yarn.lock
Labels: ready to accept

#1230 [C] Make audio player error message clearer
  client/src/components/frontend/Resource/Player/Audio.js
  client/src/theme/Components/browse/resource/_audio-player.scss
Labels: ready to accept

#1232 [B] Always show total annotation count on text thumbnail
  api/app/serializers/text_partial_serializer.rb
Labels: needs review

#1235 [B] Fix nested form button submitting on 'enter' press
  client/src/components/backend/Form/__tests__/__snapshots__/HasMany-test.js.snap
  client/src/components/backend/Project/Form/__tests__/__snapshots__/Subjects-test.js.snap
  client/src/containers/backend/Form/PredictiveInput.js
  client/src/containers/backend/Form/__tests__/__snapshots__/Collaborators-test.js.snap
  client/src/containers/backend/Project/__tests__/__snapshots__/Collaborators-test.js.snap
  client/src/containers/backend/Project/__tests__/__snapshots__/General-test.js.snap
  client/src/containers/backend/Text/__tests__/__snapshots__/Collaborators-test.js.snap
Labels: needs review

#1238 [B] Fix footer padding on mobile
  client/src/theme/Components/browse/layout/_footer-browse.scss
Labels: bug

#1234 [B] Remove meta tags from manifest spec fixture files
  api/spec/data/ingestion/manifest/section_1.html
  api/spec/data/ingestion/manifest/section_1_1.html
  api/spec/data/ingestion/manifest/section_1_1a.md
Labels: needs review

#1251 [B] Fix stylelint yarn task
  client/package.json
Labels: bug

#1249 [B] Fix syntax error in ie11
  client/package.json
  client/yarn.lock
Labels: bug

#1254 [B] Add attachment validation by type
  api/app/models/concerns/attachments.rb
Labels: needs review

#1255 [B] Create new text on every new ingestion
  api/app/controllers/concerns/validation.rb
  api/app/services/ingestions/compilers/text.rb
  api/db/migrate/20180731223301_add_reingestion_to_ingestions.rb
  api/db/schema.rb
  client/src/components/backend/Ingestion/Form/Wrapper.js
Labels: needs review

#1267 [B] Use redux store to track backend project list filter state
  client/src/actions/index.js
  client/src/actions/ui/persistentUi.js
  client/src/actions/ui/stateSnapshot.js
  client/src/containers/backend/Backend.js
  client/src/containers/backend/Dashboard.js
  client/src/containers/backend/Dashboards/Admin.js
  client/src/containers/backend/Dashboards/__tests__/Admin-test.js
  client/src/containers/reader/Reader.js
  client/src/store/reducers/ui/transitory.js
  client/src/store/reducers/ui/transitory/stateSnapshots.js
Labels: needs review

#1268 [B] Fix ProjectList.Grid throwing error when prevProps.projects is null
  client/src/components/frontend/ProjectList/Grid.js
Labels: needs revision
