Repository ManifoldScholar/manifold, pull requests merged in 2020-01, with the labels that each got.

#2522 [WIP] Convert rswag 403 tests to 401
  api/config/locales/en.yml
  api/spec/api_docs/examples/create.rb
  api/spec/api_docs/examples/destroy.rb
  api/spec/api_docs/examples/index.rb
  api/spec/api_docs/examples/show.rb
  api/spec/api_docs/examples/update.rb
  api/spec/api_docs/helpers/request.rb
  api/spec/requests/api/v1/users_spec.rb
Labels: needs review

#2514 [WIP] Document Annotation API endpoints
  api/app/serializers/serializer_registry.rb
  api/app/serializers/v1/annotation_serializer.rb
  api/spec/api_docs/definitions/resources/annotation.rb
  api/spec/requests/api/v1/annotations_spec.rb
Labels: needs review

#2527 [WIP] Document CollectionResources API endpoints
  api/app/serializers/v1/collection_resource_serializer.rb
  api/spec/api_docs/definitions/resources/collection_resource.rb
  api/spec/requests/api/v1/collection_resources_spec.rb
Labels: needs review

#2529 [WIP] Document Collaborator API endpoints
  api/app/serializers/v1/collaborator_serializer.rb
  api/spec/api_docs/definitions/resources/collaborator.rb
  api/spec/requests/api/v1/collaborators_spec.rb
Labels: needs review

#2528 [WIP] Document CollectionProjects API endpoints
  api/app/serializers/v1/collection_project_serializer.rb
  api/spec/api_docs/definitions/resources/collection_project.rb
  api/spec/requests/api/v1/collection_project_spec.rb
Labels: needs review

#2533 [WIP] Document Events API endpoints
  api/app/serializers/v1/event_serializer.rb
  api/spec/api_docs/definitions/resources/event.rb
  api/spec/requests/api/v1/events_spec.rb
Labels: needs review

#2535 [WIP] Document Makers API endpoints
  api/app/serializers/v1/maker_serializer.rb
  api/spec/api_docs/definitions/resources/maker.rb
  api/spec/requests/api/v1/makers_spec.rb
Labels: needs review

#2531 [WIP] Document Contacts API endpoint
  api/spec/requests/api/v1/contacts_spec.rb
Labels: needs review

#2547 [C] Set lockbox to standard gem release
  api/Gemfile
  api/Gemfile.lock
Labels: needs review

#2539 [WIP] Document Ingestion API endpoints
  api/app/serializers/v1/ingestion_serializer.rb
  api/spec/api_docs/definitions/resources/ingestion.rb
  api/spec/requests/api/v1/ingestions_spec.rb
Labels: needs review

#2543 [WIP] Document TwitterQuery API endpoints
  api/app/serializers/v1/twitter_query_serializer.rb
  api/spec/api_docs/definitions/resources/twitter_query.rb
  api/spec/requests/api/v1/twitter_queries_spec.rb
Labels: needs review

#2544 [WIP] Document Subject API endpoints
  api/app/serializers/v1/subject_serializer.rb
  api/spec/api_docs/definitions/resources/subject.rb
  api/spec/requests/api/v1/subjects_spec.rb
Labels: needs review

#2545 [WIP] Document Permissions API endpoints
  api/app/serializers/v1/permission_serializer.rb
  api/spec/api_docs/definitions/resources/permission.rb
  api/spec/requests/api/v1/permissions_spec.rb
Labels: needs review

#2556 [C] Adjust eager loading in development
  api/config/initializers/zzz_eager_load_in_dev.rb
Labels: bug

#2569 [WIP] Document Stylesheet API endpoints
  api/app/serializers/v1/stylesheet_serializer.rb
  api/spec/api_docs/definitions/resources/stylesheet.rb
  api/spec/requests/api/v1/stylesheets_spec.rb
Labels: needs review

#2577 [WIP] Document password related API endpoints
  api/spec/api_docs/definitions/resource.rb
  api/spec/api_docs/definitions/resources/password.rb
  api/spec/api_docs/examples/create.rb
  api/spec/api_docs/helpers/request.rb
  api/spec/requests/api/v1/passwords_spec.rb
Labels: needs review

#2579 [WIP] Document ReadingGroupMembership API endpoints
  api/app/serializers/v1/reading_group_membership_serializer.rb
  api/spec/api_docs/definitions/resources/reading_group_membership.rb
  api/spec/api_docs/examples/destroy.rb
  api/spec/requests/api/v1/reading_group_memberships_spec.rb
Labels: needs review

#2585 [WIP] Document Tags API endpoint
  api/app/serializers/v1/tag_serializer.rb
  api/spec/api_docs/definitions/resources/tag.rb
  api/spec/requests/api/v1/tags_spec.rb
Labels: needs review

#2589 [B] Fix color regressions
  client/src/frontend/components/layout/Header/PressHeader.js
  client/src/frontend/components/project-collection/Detail.js
  client/src/frontend/components/project-collection/Summary.js
  client/src/frontend/components/resource-player/Audio.js
  client/src/theme/styles/base/_appearance.scss
  client/src/theme/styles/components/backend/_button-switch.scss
  client/src/theme/styles/components/backend/list/entity/_entity-list.scss
  client/src/theme/styles/components/global/_buttons.scss
  client/src/theme/styles/components/global/_checkboxes.scss
  client/src/theme/styles/components/global/forms/_form-inputs-primary.scss
  client/src/theme/styles/components/global/forms/_list-filter.scss
  client/src/theme/styles/components/reader/control-menus/_appearance.scss
Labels: needs review

#2580 [WIP] Document Settings API endpoints
  api/app/serializers/v1/setting_serializer.rb
  api/app/services/types/serializer.rb
  api/spec/api_docs/definitions/resources/setting.rb
  api/spec/requests/api/v1/settings_spec.rb
Labels: needs review

#2599 [B] Fix Form.Date focus color in FF
  client/src/theme/styles/components/global/forms/_form-inputs-primary.scss
Labels: needs review

#2572 [WIP] Document ResourceImport API endpoints
  api/app/serializers/v1/resource_import_serializer.rb
  api/spec/api_docs/definitions/resources/resource_import.rb
  api/spec/api_docs/examples/create.rb
  api/spec/api_docs/examples/show.rb
  api/spec/api_docs/examples/update.rb
  api/spec/models/ingestion_spec.rb
  api/spec/requests/action_callouts_spec.rb
  api/spec/requests/api/v1/favorites_spec.rb
  api/spec/requests/api/v1/resource_imports_spec.rb
  api/spec/requests/comments_spec.rb
  api/spec/requests/contacts_controller_spec.rb
  api/spec/requests/content_blocks_spec.rb
  api/spec/requests/export_targets_spec.rb
  api/spec/requests/ingestion_spec.rb
  api/spec/requests/makers_spec.rb
  api/spec/requests/me/relationships/favorites_spec.rb
  api/spec/requests/me_spec.rb
  api/spec/requests/project_collections/relationships/collection_projects_controller_spec.rb
  api/spec/requests/project_collections_spec.rb
  api/spec/requests/project_exportations_spec.rb
  api/spec/requests/projects/relationships/action_callouts_spec.rb
  api/spec/requests/projects/relationships/content_blocks_spec.rb
  api/spec/requests/projects/relationships/permissions_controller_spec.rb
  api/spec/requests/projects/relationships/resource_imports_spec.rb
  api/spec/requests/projects/relationships/resources_spec.rb
  api/spec/requests/projects/relationships/text_categories_spec.rb
  api/spec/requests/projects/relationships/twitter_queries_spec.rb
  api/spec/requests/projects_spec.rb
  api/spec/requests/reading_group_memberships_spec.rb
  api/spec/requests/reading_groups_spec.rb
  api/spec/requests/resource_collections_spec.rb
  api/spec/requests/resources_spec.rb
  api/spec/requests/stylesheets_spec.rb
  api/spec/requests/text_sections/relationships/annotations_spec.rb
  api/spec/requests/users_spec.rb
  api/spec/support/requests/param_helpers.rb
  api/spec/support/shared_examples/orderable_record.rb
Labels: ready to accept

#2588 [F] Document Versions API endpoint
  api/app/serializers/v1/version_serializer.rb
  api/spec/api_docs/definitions/resources/version.rb
  api/spec/requests/api/v1/versions_spec.rb
Labels: needs review

#2593 [B] Adjust Notation.Marker click behavior
  client/src/reader/components/notation/Marker.js
Labels: needs review

#2555 [WIP] Improve Form.Upload a11y
  client/package.json
  client/src/backend/components/ingestion/form/__tests__/__snapshots__/Upload-test.js.snap
  client/src/backend/components/ingestion/form/__tests__/__snapshots__/Wrapper-test.js.snap
  client/src/backend/components/project/form/AvatarBuilder.js
  client/src/backend/components/project/form/ColorPicker.js
  client/src/backend/components/resource/form/__tests__/__snapshots__/KindAttributes-test.js.snap
  client/src/backend/components/resource/form/kind/__tests__/__snapshots__/Variants-test.js.snap
  client/src/backend/containers/project/__tests__/__snapshots__/General-test.js.snap
  client/src/backend/containers/project/__tests__/__snapshots__/ProjectPage-test.js.snap
  client/src/backend/containers/project/text/ingestion/__tests__/__snapshots__/New-test.js.snap
  client/src/backend/containers/resource-collection/__tests__/__snapshots__/General-test.js.snap
  client/src/backend/containers/resource/__tests__/__snapshots__/General-test.js.snap
  client/src/backend/containers/resource/__tests__/__snapshots__/Variants-test.js.snap
  client/src/backend/containers/text/__tests__/__snapshots__/General-test.js.snap
  client/src/backend/containers/text/ingestion/__tests__/__snapshots__/New-test.js.snap
  client/src/global/components/form/Upload/Base.js
  client/src/global/components/form/Upload/Empty.js
  client/src/global/components/form/Upload/FilePreview.js
  client/src/global/components/form/Upload/ImagePreview.js
  client/src/global/components/form/__tests__/Upload-test.js
  client/src/global/components/form/__tests__/__snapshots__/Upload-test.js.snap
  client/src/global/components/sign-in-up/UpdateForm.js
  client/src/test/setup.js
  client/src/theme/styles/components/global/forms/_form-inputs-secondary.scss
  client/src/theme/styles/components/global/forms/_shared.scss
  client/yarn.lock
Labels: ready to accept
